name: secrets-workflow.yml

on:
    push:
    workflow_dispatch:

jobs:
    secret:
        runs-on: ubuntu-latest
        steps:
            - name: Verify if the secret is being read or not
              env: 
                  SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
              run: |
                  if [ -n "$SECRET" ]; then
                      echo "The secret is set: true"
                  else
                      echo "The secret is set: false"
                  fi
            - name: Directly Print The Secret
              run: echo "Print the msg ${{ secrets.MY_SECRET_MESSAGE }}"

            - name: Use CLI Command
              run: |
                  docker login -u "$USERNAME" --password "$PASSWORD"
                  echo "done with docker login!"